version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.0
    container_name: studiahub-dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    ports:
      - "8000:8000"
    volumes:
      - ./.dynamodb:/home/dynamodblocal/data
    restart: unless-stopped

  # Tables are initialized via Node script: `npm run db:init:local`

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: studiahub-dynamodb-admin
    depends_on:
      - dynamodb-local
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    restart: unless-stopped
