service: studiahub-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true
  environment:
    S3_BUCKET: ${env:S3_BUCKET, '${self:service}-${self:provider.stage}-assets'}
    PROCESSING_QUEUE_URL:
      Ref: ProcessingQueue
    QUIZ_QUEUE_URL:
      Ref: QuizQueue
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY}
    PINECONE_ENVIRONMENT: ${env:PINECONE_ENVIRONMENT, 'us-east-1-aws'}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    STRIPE_MONTHLY_PRICE_ID: ${env:STRIPE_MONTHLY_PRICE_ID}
    STRIPE_ANNUAL_PRICE_ID: ${env:STRIPE_ANNUAL_PRICE_ID}
    ITEMS_TABLE: ${self:service}-${self:provider.stage}-items
    FILES_TABLE: ${self:service}-${self:provider.stage}-files
    QUIZ_TABLE: ${self:service}-${self:provider.stage}-quizzes
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ITEMS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FILES_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FILES_TABLE}/index/*
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.QUIZ_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.QUIZ_TABLE}/index/*
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:PutObjectAcl
          Resource:
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET}
        - Effect: Allow
          Action:
            - textract:DetectDocumentText
            - textract:AnalyzeDocument
          Resource: "*"
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - { "Fn::GetAtt": [ ProcessingQueue, Arn ] }
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - { "Fn::GetAtt": [ ProcessingQueue, Arn ] }
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - { "Fn::GetAtt": [ QuizQueue, Arn ] }
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - { "Fn::GetAtt": [ QuizQueue, Arn ] }

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    target: node20
    sourcemap: false
    platform: node
    concurrency: 4
    keepOutputDirectory: false
    packager: npm
    installExtraArgs:
      - '--production'
      - '--no-optional'
    exclude:
      - 'typescript'
      - '@types/*'
      - 'serverless*'
      - 'eslint*'
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.serverless/**/*', '.build/**/*']
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
    stages:
      - dev
  serverless-offline:
    httpPort: 4000
  dotenv:
    path: .env.${sls:stage}

functions:
  health:
    handler: src/handlers/health.handler
    events:
      - httpApi:
          path: /health
          method: GET
  filesGet:
    handler: src/handlers/files/fileStatus.get
    events:
      - httpApi:
          path: /files/{key+}
          method: GET
  presignedUrl:
    handler: src/handlers/files/presignedUrl.generatePresignedUrl
    events:
      - httpApi:
          path: /upload/presigned
          method: POST
  confirmUpload:
    handler: src/handlers/files/presignedUrl.confirmUpload
    events:
      - httpApi:
          path: /upload/confirm
          method: POST
  filesList:
    handler: src/handlers/files/filesList.list
    events:
      - httpApi:
          path: /files
          method: GET
  filesDelete:
    handler: src/handlers/files/filesList.deleteFile
    events:
      - httpApi:
          path: /files/{id}
          method: DELETE
  filesToggle:
    handler: src/handlers/files/filesList.toggleFile
    events:
      - httpApi:
          path: /files/{id}/toggle
          method: PATCH

  generateQuiz:
    handler: src/handlers/quiz/generateQuiz.generateQuiz
    timeout: 25
    memorySize: 384
    events:
      - httpApi:
          path: /quiz/generate
          method: POST

  quizStatus:
    handler: src/handlers/quiz/quizStatus.getQuizStatus
    timeout: 8
    memorySize: 192
    events:
      - httpApi:
          path: /quiz/{id}/status
          method: GET

  userQuizzes:
    handler: src/handlers/quiz/quizStatus.getUserQuizzes
    timeout: 10
    memorySize: 256
    events:
      - httpApi:
          path: /quiz/user
          method: GET

  deleteQuiz:
    handler: src/handlers/quiz/deleteQuiz.deleteQuiz
    timeout: 8
    memorySize: 192
    events:
      - httpApi:
          path: /quiz/{id}
          method: DELETE

  quizWorker:
    handler: src/handlers/quiz/quizWorker.handler
    timeout: 240
    memorySize: 768
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ QuizQueue, Arn ]
          batchSize: 1
          maximumBatchingWindow: 0

  queueProcessor:
    handler: src/handlers/files/queue.process
    timeout: 900
    memorySize: 2048
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ ProcessingQueue, Arn ]
          batchSize: 1

resources:
  Resources:    
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.FILES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: key-index
            KeySchema:
              - AttributeName: key
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    QuizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.QUIZ_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: user-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        
    ProcessingDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-processing-dlq
        MessageRetentionPeriod: 1209600
    ProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-processing
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn: { "Fn::GetAtt": [ ProcessingDLQ, Arn ] }
          maxReceiveCount: 3

    QuizDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-quiz-dlq
        MessageRetentionPeriod: 1209600
    QuizQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-quiz
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn: { "Fn::GetAtt": [ QuizDLQ, Arn ] }
          maxReceiveCount: 3


package:
  patterns:
    - '!test/**'
    - '!**/*.md'
    - '!**/*.txt'
    - '!**/LICENSE*'
    - '!**/CHANGELOG*'
    - '!**/.git/**'
    - '!**/docs/**'
    - '!**/examples/**'
    - '!**/coverage/**'
    - '!**/.nyc_output/**'
    - '!**/prisma/**'
    - '!**/*.prisma'
    - '!**/migrations/**'
    - '!**/.serverless/**'
    - '!**/.build/**'
    - '!**/node_modules/.cache/**'
  individually: true
  excludeDevDependencies: true
